"""Seed corpus of existing market solutions for the originality checker.

PRD §5.6 — the vector DB needs example solutions to compare against. This is a
curated set (~200 items) spanning the competition solution domains: education,
government, healthcare, business, manufacturing, agriculture, smart city,
sustainability, fintech, and general/social. Used as the offline fallback when
web search (Tavily) is not configured or unavailable.
"""

SEED_SOLUSI: list[dict] = [
    # ---------------- Education ----------------
    {"id": "edu1", "nama": "Platform Belajar Adaptif", "deskripsi": "Sistem pembelajaran daring yang menyesuaikan materi dan latihan berdasarkan kemampuan tiap siswa secara personal."},
    {"id": "edu2", "nama": "Tutor AI Percakapan", "deskripsi": "Asisten belajar berbasis chatbot yang menjawab pertanyaan siswa dan menjelaskan konsep langkah demi langkah."},
    {"id": "edu3", "nama": "Aplikasi Latihan Soal UTBK", "deskripsi": "Bank soal dan tryout adaptif untuk persiapan ujian masuk perguruan tinggi lengkap dengan pembahasan."},
    {"id": "edu4", "nama": "Penilai Esai Otomatis", "deskripsi": "Sistem AI yang menilai esai siswa dari sisi struktur, argumentasi, dan tata bahasa serta memberi umpan balik."},
    {"id": "edu5", "nama": "Platform Kursus Keterampilan Digital", "deskripsi": "Marketplace kelas daring untuk keterampilan teknologi dengan sertifikat dan proyek portofolio."},
    {"id": "edu6", "nama": "Aplikasi Belajar Bahasa Interaktif", "deskripsi": "Latihan kosakata dan percakapan bahasa asing berbasis gamifikasi dan pengenalan suara."},
    {"id": "edu7", "nama": "Asisten Skripsi Mahasiswa", "deskripsi": "Alat bantu menyusun kerangka penelitian, mencari referensi, dan memeriksa metodologi skripsi."},
    {"id": "edu8", "nama": "Simulator Sidang Skripsi", "deskripsi": "Simulasi tanya jawab dengan dosen penguji virtual untuk melatih mahasiswa menghadapi sidang."},
    {"id": "edu9", "nama": "Platform Bimbingan Belajar Daring", "deskripsi": "Menghubungkan siswa dengan tutor privat melalui video call dan penjadwalan otomatis."},
    {"id": "edu10", "nama": "Aplikasi Manajemen Kelas Guru", "deskripsi": "Membantu guru mengelola absensi, tugas, dan nilai siswa dalam satu dashboard."},
    {"id": "edu11", "nama": "Ringkas Materi Kuliah AI", "deskripsi": "Mengubah rekaman kuliah atau PDF menjadi ringkasan, kartu belajar, dan kuis otomatis."},
    {"id": "edu12", "nama": "Platform Beasiswa Terpadu", "deskripsi": "Agregator informasi beasiswa yang mencocokkan profil pelajar dengan peluang yang relevan."},
    {"id": "edu13", "nama": "Aplikasi Membaca Anak", "deskripsi": "Melatih literasi anak usia dini dengan cerita interaktif dan umpan balik pengucapan."},
    {"id": "edu14", "nama": "Sistem Deteksi Kecurangan Ujian Daring", "deskripsi": "Memantau ujian online melalui webcam untuk mendeteksi perilaku mencurigakan."},
    {"id": "edu15", "nama": "Platform Kolaborasi Riset Kampus", "deskripsi": "Menghubungkan mahasiswa dan dosen untuk proyek penelitian bersama dan berbagi data."},
    {"id": "edu16", "nama": "Perencana Karier Pelajar", "deskripsi": "Membantu siswa memilih jurusan dan jalur karier berdasarkan minat dan bakat."},
    {"id": "edu17", "nama": "Aplikasi Kelas Coding Anak", "deskripsi": "Mengajarkan pemrograman dasar untuk anak lewat blok visual dan tantangan bertingkat."},
    {"id": "edu18", "nama": "Sistem LMS Sekolah", "deskripsi": "Platform manajemen pembelajaran untuk sekolah dengan modul materi, tugas, dan rapor digital."},
    {"id": "edu19", "nama": "Asisten Pembuat RPP Guru", "deskripsi": "Menghasilkan rencana pelaksanaan pembelajaran otomatis sesuai kurikulum dan mata pelajaran."},
    {"id": "edu20", "nama": "Platform Magang Mahasiswa", "deskripsi": "Menghubungkan mahasiswa dengan lowongan magang dari industri yang sesuai program studi."},
    {"id": "edu21", "nama": "Aplikasi Flashcard Cerdas", "deskripsi": "Sistem hafalan dengan pengulangan berjarak untuk mengingat materi lebih efektif."},
    {"id": "edu22", "nama": "Simulasi Laboratorium Virtual", "deskripsi": "Praktikum sains virtual untuk sekolah dengan keterbatasan alat laboratorium."},
    {"id": "edu23", "nama": "Platform Pelatihan Guru Daring", "deskripsi": "Kursus pengembangan profesional untuk guru beserta komunitas berbagi praktik mengajar."},
    {"id": "edu24", "nama": "Aplikasi Presentasi & Public Speaking", "deskripsi": "Melatih kemampuan presentasi dengan analisis intonasi, kecepatan bicara, dan kata pengisi."},
    {"id": "edu25", "nama": "Pendamping Belajar Anak Berkebutuhan Khusus", "deskripsi": "Materi belajar yang disesuaikan untuk anak dengan kebutuhan pendidikan khusus."},

    # ---------------- Government ----------------
    {"id": "gov1", "nama": "Portal Layanan Publik Terpadu", "deskripsi": "Aplikasi satu pintu untuk mengakses layanan administrasi pemerintah secara daring."},
    {"id": "gov2", "nama": "Aplikasi Pengaduan Warga", "deskripsi": "Kanal pelaporan masalah publik seperti jalan rusak dan sampah langsung ke dinas terkait."},
    {"id": "gov3", "nama": "Chatbot Layanan Dukcapil", "deskripsi": "Asisten virtual yang memandu warga mengurus dokumen kependudukan dan menjawab pertanyaan."},
    {"id": "gov4", "nama": "Sistem Antrian Online Puskesmas", "deskripsi": "Pendaftaran dan antrian daring untuk fasilitas kesehatan milik pemerintah."},
    {"id": "gov5", "nama": "Platform Transparansi Anggaran Desa", "deskripsi": "Menampilkan penggunaan dana desa secara terbuka agar dapat diawasi masyarakat."},
    {"id": "gov6", "nama": "Aplikasi Pajak Daerah", "deskripsi": "Memudahkan warga menghitung dan membayar pajak daerah secara elektronik."},
    {"id": "gov7", "nama": "Sistem Perizinan Usaha Online", "deskripsi": "Mempercepat pengurusan izin usaha kecil melalui alur digital yang sederhana."},
    {"id": "gov8", "nama": "Peta Rawan Bencana", "deskripsi": "Sistem informasi geografis untuk memetakan dan memperingatkan wilayah rawan bencana."},
    {"id": "gov9", "nama": "Aplikasi Pemilu & Partisipasi Warga", "deskripsi": "Informasi calon, lokasi TPS, dan edukasi pemilih untuk meningkatkan partisipasi publik."},
    {"id": "gov10", "nama": "Sistem Manajemen Surat Dinas", "deskripsi": "Digitalisasi disposisi dan arsip surat di instansi pemerintah."},
    {"id": "gov11", "nama": "Analisis Sentimen Kebijakan Publik", "deskripsi": "Memantau opini masyarakat terhadap kebijakan pemerintah dari media sosial."},
    {"id": "gov12", "nama": "Aplikasi Bantuan Sosial Tepat Sasaran", "deskripsi": "Membantu penyaluran bantuan sosial dengan verifikasi data penerima yang lebih akurat."},
    {"id": "gov13", "nama": "Portal Data Terbuka Pemerintah", "deskripsi": "Menyediakan data publik yang dapat diakses dan dianalisis oleh masyarakat dan peneliti."},
    {"id": "gov14", "nama": "Sistem Monitoring Proyek Infrastruktur", "deskripsi": "Melacak progres dan realisasi proyek pembangunan pemerintah secara real time."},
    {"id": "gov15", "nama": "Aplikasi Lapor Pungli", "deskripsi": "Kanal pelaporan anonim untuk praktik pungutan liar di layanan publik."},
    {"id": "gov16", "nama": "Asisten Regulasi Hukum", "deskripsi": "Mesin pencari dan penjelas peraturan perundang-undangan untuk masyarakat awam."},
    {"id": "gov17", "nama": "Sistem Pendaftaran Sekolah Zonasi", "deskripsi": "Otomasi pendaftaran peserta didik baru berbasis zonasi yang transparan."},
    {"id": "gov18", "nama": "Aplikasi Pariwisata Daerah", "deskripsi": "Promosi destinasi wisata lokal dengan informasi, rute, dan pemesanan terpadu."},
    {"id": "gov19", "nama": "Sistem Manajemen ASN", "deskripsi": "Mengelola kinerja, absensi, dan pengembangan aparatur sipil negara."},
    {"id": "gov20", "nama": "Peta Interaktif Fasilitas Umum", "deskripsi": "Menampilkan lokasi fasilitas publik terdekat beserta jam operasional dan ulasan."},

    # ---------------- Healthcare ----------------
    {"id": "hlt1", "nama": "Telemedicine Daerah Terpencil", "deskripsi": "Layanan konsultasi kesehatan jarak jauh yang menghubungkan pasien di daerah terpencil dengan dokter melalui video call."},
    {"id": "hlt2", "nama": "Aplikasi Pengingat Minum Obat", "deskripsi": "Membantu pasien mematuhi jadwal minum obat dengan pengingat dan catatan riwayat."},
    {"id": "hlt3", "nama": "Deteksi Dini Penyakit dari Gejala", "deskripsi": "Sistem triase yang memberi rekomendasi awal berdasarkan gejala yang dilaporkan pengguna."},
    {"id": "hlt4", "nama": "Platform Kesehatan Mental", "deskripsi": "Konseling daring, jurnal suasana hati, dan latihan relaksasi untuk kesehatan mental."},
    {"id": "hlt5", "nama": "Analisis Citra Medis AI", "deskripsi": "Membantu dokter membaca hasil rontgen atau CT scan untuk mendeteksi kelainan."},
    {"id": "hlt6", "nama": "Aplikasi Pemantau Gizi", "deskripsi": "Melacak asupan kalori dan nutrisi harian dengan pemindaian foto makanan."},
    {"id": "hlt7", "nama": "Sistem Antrian & Rekam Medis Klinik", "deskripsi": "Digitalisasi rekam medis dan antrian pasien untuk klinik kecil."},
    {"id": "hlt8", "nama": "Platform Donor Darah", "deskripsi": "Menghubungkan pendonor dengan permintaan darah mendesak berdasarkan lokasi dan golongan."},
    {"id": "hlt9", "nama": "Aplikasi Pemantau Kehamilan", "deskripsi": "Panduan mingguan kehamilan, pengingat kontrol, dan deteksi tanda bahaya untuk ibu hamil."},
    {"id": "hlt10", "nama": "Deteksi Stunting Balita", "deskripsi": "Memantau pertumbuhan balita dan memberi peringatan dini risiko stunting bagi orang tua."},
    {"id": "hlt11", "nama": "Asisten Diagnosa Penyakit Kulit", "deskripsi": "Klasifikasi kondisi kulit dari foto beserta rekomendasi konsultasi lanjutan."},
    {"id": "hlt12", "nama": "Platform Apotek Online", "deskripsi": "Pemesanan obat dengan resep digital dan pengantaran ke rumah."},
    {"id": "hlt13", "nama": "Aplikasi Kebugaran Personal", "deskripsi": "Program latihan dan diet yang dipersonalisasi dengan pelacakan progres."},
    {"id": "hlt14", "nama": "Sistem Manajemen Rumah Sakit", "deskripsi": "Mengelola tempat tidur, jadwal dokter, dan alur pasien di rumah sakit."},
    {"id": "hlt15", "nama": "Pengingat & Jadwal Imunisasi", "deskripsi": "Membantu orang tua memantau jadwal imunisasi anak sesuai program pemerintah."},
    {"id": "hlt16", "nama": "Platform Lansia & Perawatan", "deskripsi": "Menghubungkan keluarga dengan perawat serta memantau kondisi kesehatan lansia."},
    {"id": "hlt17", "nama": "Analisis Suara untuk Deteksi Batuk", "deskripsi": "Mendeteksi indikasi penyakit pernapasan dari pola suara batuk pengguna."},
    {"id": "hlt18", "nama": "Aplikasi Manajemen Diabetes", "deskripsi": "Mencatat kadar gula darah, pola makan, dan memberi saran pengelolaan diabetes."},
    {"id": "hlt19", "nama": "Platform Edukasi Kesehatan Masyarakat", "deskripsi": "Menyebarkan informasi kesehatan terverifikasi untuk melawan hoaks medis."},
    {"id": "hlt20", "nama": "Sistem Rujukan Pasien Terpadu", "deskripsi": "Mempercepat rujukan antar fasilitas kesehatan dengan berbagi data pasien yang aman."},

    # ---------------- Business ----------------
    {"id": "biz1", "nama": "Marketplace UMKM Lokal", "deskripsi": "Platform yang membantu pelaku UMKM memasarkan produk secara daring dengan dukungan logistik dan pembayaran terintegrasi."},
    {"id": "biz2", "nama": "Aplikasi Kasir & Inventaris UMKM", "deskripsi": "Sistem point-of-sale sederhana dengan pencatatan stok dan laporan penjualan."},
    {"id": "biz3", "nama": "Asisten Pembukuan Otomatis", "deskripsi": "Mencatat transaksi dan menyusun laporan keuangan sederhana untuk usaha kecil."},
    {"id": "biz4", "nama": "Platform Manajemen Karyawan", "deskripsi": "Mengelola absensi, penggajian, dan cuti karyawan untuk perusahaan kecil menengah."},
    {"id": "biz5", "nama": "Generator Konten Pemasaran AI", "deskripsi": "Membuat caption, materi promosi, dan gambar iklan untuk bisnis secara otomatis."},
    {"id": "biz6", "nama": "Chatbot Customer Service", "deskripsi": "Asisten layanan pelanggan otomatis yang menjawab pertanyaan umum lintas kanal."},
    {"id": "biz7", "nama": "Analisis Ulasan Pelanggan", "deskripsi": "Merangkum sentimen dan keluhan pelanggan dari ulasan untuk perbaikan produk."},
    {"id": "biz8", "nama": "Platform Reservasi & Booking", "deskripsi": "Sistem pemesanan online untuk salon, restoran, atau jasa dengan pengingat otomatis."},
    {"id": "biz9", "nama": "Aplikasi Manajemen Proyek Tim", "deskripsi": "Mengelola tugas, tenggat, dan kolaborasi tim dalam satu ruang kerja."},
    {"id": "biz10", "nama": "Prediksi Permintaan Stok", "deskripsi": "Memperkirakan kebutuhan stok berdasarkan tren penjualan agar tidak kehabisan barang."},
    {"id": "biz11", "nama": "Platform Franchise Digital", "deskripsi": "Memudahkan pengelolaan banyak cabang waralaba dari satu dashboard terpusat."},
    {"id": "biz12", "nama": "Asisten Riset Pasar", "deskripsi": "Mengumpulkan dan menganalisis data kompetitor serta tren untuk keputusan bisnis."},
    {"id": "biz13", "nama": "Aplikasi Manajemen Rantai Pasok", "deskripsi": "Melacak alur barang dari pemasok hingga konsumen untuk efisiensi distribusi."},
    {"id": "biz14", "nama": "Platform Loyalty & Poin Pelanggan", "deskripsi": "Program loyalitas digital dengan poin, kupon, dan promo untuk menjaga pelanggan."},
    {"id": "biz15", "nama": "Generator Proposal Bisnis", "deskripsi": "Menyusun proposal dan business plan otomatis dari input ide pengguna."},
    {"id": "biz16", "nama": "Aplikasi Faktur & Penagihan", "deskripsi": "Membuat invoice profesional dan mengingatkan pembayaran yang jatuh tempo."},
    {"id": "biz17", "nama": "Platform Dropship & Reseller", "deskripsi": "Menghubungkan reseller dengan pemasok tanpa perlu menyetok barang sendiri."},
    {"id": "biz18", "nama": "Analisis Penetapan Harga Dinamis", "deskripsi": "Merekomendasikan harga optimal berdasarkan permintaan, stok, dan kompetitor."},
    {"id": "biz19", "nama": "CRM untuk Usaha Kecil", "deskripsi": "Mengelola data pelanggan, prospek, dan aktivitas penjualan secara terpusat."},
    {"id": "biz20", "nama": "Platform Ekspor UMKM", "deskripsi": "Membantu UMKM menembus pasar ekspor dengan panduan regulasi dan pembeli global."},

    # ---------------- Manufacturing ----------------
    {"id": "mfg1", "nama": "Pemantau Mesin Prediktif", "deskripsi": "Mendeteksi potensi kerusakan mesin lebih awal dari data sensor untuk mengurangi downtime."},
    {"id": "mfg2", "nama": "Inspeksi Kualitas Produk Visual", "deskripsi": "Mendeteksi cacat produk di lini produksi menggunakan kamera dan computer vision."},
    {"id": "mfg3", "nama": "Sistem Manajemen Produksi", "deskripsi": "Menjadwalkan dan memantau proses produksi pabrik secara real time."},
    {"id": "mfg4", "nama": "Optimasi Konsumsi Energi Pabrik", "deskripsi": "Menganalisis pemakaian energi mesin dan menyarankan penghematan."},
    {"id": "mfg5", "nama": "Pelacakan Aset & Peralatan", "deskripsi": "Memantau lokasi dan kondisi aset pabrik dengan tag IoT."},
    {"id": "mfg6", "nama": "Sistem Keselamatan Kerja Berbasis AI", "deskripsi": "Mendeteksi pelanggaran keselamatan seperti tidak memakai APD dari kamera CCTV."},
    {"id": "mfg7", "nama": "Perencana Perawatan Berkala", "deskripsi": "Menjadwalkan pemeliharaan mesin agar tidak mengganggu jadwal produksi."},
    {"id": "mfg8", "nama": "Digital Twin Lini Produksi", "deskripsi": "Simulasi digital pabrik untuk menguji perubahan proses sebelum diterapkan."},
    {"id": "mfg9", "nama": "Manajemen Gudang Otomatis", "deskripsi": "Mengoptimalkan penyimpanan dan pengambilan barang di gudang dengan robotika."},
    {"id": "mfg10", "nama": "Prediksi Cacat Bahan Baku", "deskripsi": "Menganalisis kualitas bahan baku untuk mencegah cacat produk sejak awal."},
    {"id": "mfg11", "nama": "Sistem Pelacakan Batch Produksi", "deskripsi": "Menelusuri asal dan riwayat tiap batch produk untuk penarikan yang cepat."},
    {"id": "mfg12", "nama": "Optimasi Tata Letak Pabrik", "deskripsi": "Merancang alur kerja pabrik yang paling efisien menggunakan simulasi."},
    {"id": "mfg13", "nama": "Aplikasi Manajemen Order Produksi", "deskripsi": "Mengelola pesanan pelanggan hingga penjadwalan produksi dan pengiriman."},
    {"id": "mfg14", "nama": "Analisis Produktivitas Pekerja", "deskripsi": "Memantau output lini produksi untuk menemukan hambatan proses."},
    {"id": "mfg15", "nama": "Sistem Pengendalian Mutu Terpadu", "deskripsi": "Mendokumentasikan dan menganalisis data mutu untuk sertifikasi standar industri."},

    # ---------------- Agriculture ----------------
    {"id": "agri1", "nama": "Platform Marketplace Petani", "deskripsi": "Aplikasi yang menghubungkan petani langsung ke pembeli untuk memangkas rantai tengkulak dan menstabilkan harga hasil panen."},
    {"id": "agri2", "nama": "Aplikasi Deteksi Dini Penyakit Tanaman", "deskripsi": "Aplikasi berbasis kamera ponsel yang mengklasifikasikan penyakit daun tanaman dan memberi rekomendasi penanganan bagi petani."},
    {"id": "agri3", "nama": "Sistem Irigasi Pintar", "deskripsi": "Mengatur penyiraman otomatis berdasarkan kelembapan tanah dan prakiraan cuaca."},
    {"id": "agri4", "nama": "Prediksi Cuaca & Musim Tanam", "deskripsi": "Memberi rekomendasi waktu tanam terbaik berdasarkan data cuaca lokal."},
    {"id": "agri5", "nama": "Platform Pembiayaan Petani", "deskripsi": "Menghubungkan petani dengan modal usaha dan asuransi gagal panen."},
    {"id": "agri6", "nama": "Drone Pemantau Lahan", "deskripsi": "Memantau kesehatan tanaman dan estimasi hasil panen dari citra udara."},
    {"id": "agri7", "nama": "Aplikasi Pencatatan Ternak", "deskripsi": "Memantau kesehatan, pakan, dan produktivitas ternak bagi peternak."},
    {"id": "agri8", "nama": "Sistem Rekomendasi Pupuk", "deskripsi": "Menyarankan dosis pupuk optimal berdasarkan jenis tanah dan tanaman."},
    {"id": "agri9", "nama": "Marketplace Alat & Bibit Pertanian", "deskripsi": "Menyediakan sarana produksi pertanian dengan harga transparan bagi petani."},
    {"id": "agri10", "nama": "Platform Budidaya Perikanan", "deskripsi": "Memantau kualitas air dan pakan pada kolam atau tambak secara digital."},
    {"id": "agri11", "nama": "Sistem Rantai Dingin Hasil Tani", "deskripsi": "Memantau suhu penyimpanan dan distribusi produk pertanian agar tidak rusak."},
    {"id": "agri12", "nama": "Aplikasi Prediksi Harga Komoditas", "deskripsi": "Memperkirakan pergerakan harga komoditas pangan untuk membantu petani menjual."},
    {"id": "agri13", "nama": "Hidroponik Pintar Rumahan", "deskripsi": "Mengelola tanaman hidroponik otomatis dengan sensor nutrisi dan cahaya."},
    {"id": "agri14", "nama": "Platform Agrowisata", "deskripsi": "Mempromosikan destinasi wisata pertanian dan menghubungkan dengan wisatawan."},
    {"id": "agri15", "nama": "Sistem Ketertelusuran Pangan", "deskripsi": "Melacak asal-usul produk pangan dari kebun hingga meja konsumen."},

    # ---------------- Smart City ----------------
    {"id": "city1", "nama": "Aplikasi Ride-sharing Kampus", "deskripsi": "Layanan berbagi tumpangan antar mahasiswa dalam satu kampus untuk menekan biaya transportasi dan emisi karbon."},
    {"id": "city2", "nama": "Sistem Manajemen Lalu Lintas Pintar", "deskripsi": "Mengoptimalkan lampu lalu lintas berdasarkan kepadatan kendaraan real time."},
    {"id": "city3", "nama": "Aplikasi Transportasi Umum Terpadu", "deskripsi": "Menampilkan rute, jadwal, dan pembayaran angkutan umum dalam satu aplikasi."},
    {"id": "city4", "nama": "Pemantau Kualitas Udara Kota", "deskripsi": "Menyajikan data polusi udara real time beserta peringatan kesehatan."},
    {"id": "city5", "nama": "Sistem Parkir Pintar", "deskripsi": "Menunjukkan ketersediaan slot parkir dan pembayaran nontunai."},
    {"id": "city6", "nama": "Aplikasi Pelaporan Infrastruktur Kota", "deskripsi": "Warga melaporkan kerusakan fasilitas kota lengkap dengan foto dan lokasi."},
    {"id": "city7", "nama": "Sistem Penerangan Jalan Adaptif", "deskripsi": "Mengatur intensitas lampu jalan otomatis untuk hemat energi."},
    {"id": "city8", "nama": "Platform Keamanan Lingkungan", "deskripsi": "Sistem CCTV pintar dan panic button untuk keamanan lingkungan warga."},
    {"id": "city9", "nama": "Prediksi Banjir Perkotaan", "deskripsi": "Memberi peringatan dini banjir berdasarkan data curah hujan dan ketinggian air."},
    {"id": "city10", "nama": "Aplikasi Navigasi Difabel", "deskripsi": "Rute ramah difabel dengan informasi aksesibilitas fasilitas umum."},
    {"id": "city11", "nama": "Sistem Manajemen Sampah Kota", "deskripsi": "Mengoptimalkan rute pengangkutan sampah berdasarkan tingkat isi tempat sampah."},
    {"id": "city12", "nama": "Platform Sewa Sepeda & Skuter", "deskripsi": "Layanan mikromobilitas berbagi untuk transportasi jarak pendek dalam kota."},
    {"id": "city13", "nama": "Dashboard Kota Cerdas", "deskripsi": "Memantau indikator kota seperti lalu lintas, energi, dan layanan publik terpadu."},
    {"id": "city14", "nama": "Aplikasi Wisata Kota Interaktif", "deskripsi": "Pemandu wisata digital dengan rute, sejarah, dan rekomendasi tempat."},
    {"id": "city15", "nama": "Sistem Pemantau Kepadatan Keramaian", "deskripsi": "Menghitung kepadatan pengunjung di ruang publik untuk manajemen kerumunan."},

    # ---------------- Sustainability ----------------
    {"id": "sus1", "nama": "Aplikasi Manajemen Sampah Daur Ulang", "deskripsi": "Aplikasi yang menghubungkan rumah tangga dengan bank sampah untuk penjemputan sampah daur ulang dan reward poin."},
    {"id": "sus2", "nama": "Platform Jual Beli Barang Bekas", "deskripsi": "Marketplace barang preloved untuk memperpanjang usia pakai produk."},
    {"id": "sus3", "nama": "Pelacak Jejak Karbon Pribadi", "deskripsi": "Menghitung emisi karbon dari aktivitas harian dan menyarankan pengurangan."},
    {"id": "sus4", "nama": "Aplikasi Donasi Makanan Berlebih", "deskripsi": "Menyalurkan makanan berlebih dari restoran ke yang membutuhkan untuk kurangi limbah."},
    {"id": "sus5", "nama": "Platform Energi Surya Rumahan", "deskripsi": "Memantau produksi dan konsumsi panel surya serta estimasi penghematan."},
    {"id": "sus6", "nama": "Sistem Pemilahan Sampah Otomatis", "deskripsi": "Mengklasifikasikan jenis sampah menggunakan computer vision untuk daur ulang."},
    {"id": "sus7", "nama": "Marketplace Produk Ramah Lingkungan", "deskripsi": "Menjual produk berkelanjutan dengan label dampak lingkungan yang jelas."},
    {"id": "sus8", "nama": "Aplikasi Penghematan Air", "deskripsi": "Memantau pemakaian air rumah tangga dan memberi tips konservasi."},
    {"id": "sus9", "nama": "Platform Penanaman Pohon Digital", "deskripsi": "Memungkinkan pengguna mendanai dan memantau penanaman pohon untuk reboisasi."},
    {"id": "sus10", "nama": "Sistem Pemantau Emisi Industri", "deskripsi": "Memonitor emisi gas buang pabrik untuk kepatuhan lingkungan."},
    {"id": "sus11", "nama": "Aplikasi Tukar Barang Komunitas", "deskripsi": "Platform barter barang antar warga untuk mengurangi konsumsi baru."},
    {"id": "sus12", "nama": "Pelacak Keanekaragaman Hayati", "deskripsi": "Mengumpulkan data flora fauna dari warga untuk konservasi berbasis sains."},
    {"id": "sus13", "nama": "Platform Kredit Karbon UMKM", "deskripsi": "Membantu usaha kecil mengukur dan memperdagangkan kredit karbon."},
    {"id": "sus14", "nama": "Aplikasi Kompos Rumah Tangga", "deskripsi": "Memandu warga mengolah sampah organik menjadi kompos di rumah."},
    {"id": "sus15", "nama": "Sistem Pemantau Kualitas Air Sungai", "deskripsi": "Memantau pencemaran sungai dengan sensor dan pelaporan warga."},

    # ---------------- Fintech ----------------
    {"id": "fin1", "nama": "Dompet Digital Tabungan Pelajar", "deskripsi": "Layanan keuangan yang membantu pelajar menabung dan mengelola uang saku dengan fitur target tabungan dan literasi finansial."},
    {"id": "fin2", "nama": "Aplikasi Pencatat Keuangan Pribadi", "deskripsi": "Mencatat pemasukan dan pengeluaran serta memberi analisis pola belanja."},
    {"id": "fin3", "nama": "Platform Donasi Transparan Blockchain", "deskripsi": "Sistem penggalangan dana amal yang melacak aliran donasi secara transparan menggunakan buku besar terdistribusi."},
    {"id": "fin4", "nama": "Aplikasi Investasi Mikro", "deskripsi": "Memungkinkan investasi reksa dana atau emas mulai dari nominal kecil."},
    {"id": "fin5", "nama": "Platform P2P Lending UMKM", "deskripsi": "Menghubungkan pemberi pinjaman dengan UMKM yang butuh modal usaha."},
    {"id": "fin6", "nama": "Asisten Perencana Keuangan AI", "deskripsi": "Memberi saran anggaran dan tujuan keuangan berdasarkan profil pengguna."},
    {"id": "fin7", "nama": "Sistem Pembayaran QRIS Terpadu", "deskripsi": "Memudahkan pedagang menerima pembayaran nontunai lintas dompet digital."},
    {"id": "fin8", "nama": "Aplikasi Arisan Digital", "deskripsi": "Mengelola arisan kelompok secara transparan dengan pembayaran otomatis."},
    {"id": "fin9", "nama": "Deteksi Penipuan Transaksi", "deskripsi": "Mengidentifikasi transaksi mencurigakan secara real time untuk mencegah fraud."},
    {"id": "fin10", "nama": "Platform Zakat & Sedekah Digital", "deskripsi": "Menghitung dan menyalurkan zakat serta sedekah ke lembaga terpercaya."},
    {"id": "fin11", "nama": "Aplikasi Patungan & Split Bill", "deskripsi": "Membagi tagihan bersama teman dan melacak utang piutang antar pengguna."},
    {"id": "fin12", "nama": "Skoring Kredit Alternatif", "deskripsi": "Menilai kelayakan kredit menggunakan data alternatif bagi yang tak punya riwayat bank."},
    {"id": "fin13", "nama": "Platform Asuransi Mikro", "deskripsi": "Menyediakan produk asuransi terjangkau untuk pekerja informal."},
    {"id": "fin14", "nama": "Aplikasi Tagihan & Langganan", "deskripsi": "Mengingatkan dan membayar tagihan rutin serta memantau langganan aktif."},
    {"id": "fin15", "nama": "Edukasi Investasi Interaktif", "deskripsi": "Simulasi dan kelas investasi untuk meningkatkan literasi keuangan pemula."},

    # ---------------- General / Social ----------------
    {"id": "gen1", "nama": "Asisten Karier Berbasis AI", "deskripsi": "Aplikasi yang menganalisis CV dan minat pengguna lalu merekomendasikan jalur karier serta pelatihan yang relevan."},
    {"id": "gen2", "nama": "Platform Relawan & Kegiatan Sosial", "deskripsi": "Menghubungkan relawan dengan kegiatan sosial dan organisasi nirlaba."},
    {"id": "gen3", "nama": "Aplikasi Pencari Kerja Lokal", "deskripsi": "Mempertemukan pencari kerja dengan lowongan di sekitar tempat tinggal."},
    {"id": "gen4", "nama": "Generator CV & Portofolio", "deskripsi": "Membuat CV profesional dan halaman portofolio otomatis dari input pengguna."},
    {"id": "gen5", "nama": "Platform Komunitas Hobi", "deskripsi": "Wadah berkumpul dan berbagi bagi komunitas dengan minat yang sama."},
    {"id": "gen6", "nama": "Aplikasi Terjemahan Bahasa Daerah", "deskripsi": "Menerjemahkan dan melestarikan bahasa daerah Indonesia dengan bantuan AI."},
    {"id": "gen7", "nama": "Asisten Penulisan & Ringkasan", "deskripsi": "Membantu menulis, menyunting, dan meringkas dokumen secara otomatis."},
    {"id": "gen8", "nama": "Platform Berbagi Kendaraan Antar Kota", "deskripsi": "Menghubungkan penumpang dengan pengemudi yang searah untuk berbagi biaya perjalanan."},
    {"id": "gen9", "nama": "Aplikasi Manajemen Acara", "deskripsi": "Mengelola undangan, tiket, dan jadwal acara dalam satu platform."},
    {"id": "gen10", "nama": "Sistem Pencarian Barang Hilang", "deskripsi": "Menghubungkan penemu dan pemilik barang hilang berbasis lokasi."},
    {"id": "gen11", "nama": "Platform Mentoring Profesional", "deskripsi": "Menghubungkan mentee dengan mentor berpengalaman di berbagai bidang."},
    {"id": "gen12", "nama": "Aplikasi Resep & Perencana Menu", "deskripsi": "Menyarankan resep dari bahan yang tersedia dan menyusun rencana makan."},
    {"id": "gen13", "nama": "Asisten Hukum untuk Masyarakat", "deskripsi": "Memberi informasi hukum dasar dan template dokumen bagi masyarakat awam."},
    {"id": "gen14", "nama": "Platform Crowdfunding Proyek Kreatif", "deskripsi": "Menggalang dana untuk proyek kreatif dan sosial dari masyarakat luas."},
    {"id": "gen15", "nama": "Aplikasi Pengingat & Produktivitas", "deskripsi": "Mengatur tugas, kebiasaan, dan fokus kerja dengan teknik manajemen waktu."},
]


def seed(embedder, store) -> int:
    """Populate the store if empty. Returns number of items indexed (0 if skipped)."""
    if store.count() > 0:
        return 0
    ids = [s["id"] for s in SEED_SOLUSI]
    texts = [f"{s['nama']}. {s['deskripsi']}" for s in SEED_SOLUSI]
    metadatas = [{"nama": s["nama"], "deskripsi": s["deskripsi"]} for s in SEED_SOLUSI]
    vectors = embedder.embed(texts)
    store.add(ids=ids, vectors=vectors, metadatas=metadatas)
    return len(ids)
